# Generated by Django 5.0.7 on 2024-08-04 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
